name: Terraform CI/CD

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

permissions:
  contents: write
  pull_request: write
  
jobs:
  terraformlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: configure aws   
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.12.0

      - name: terraform initialize
        id: init
        working-directory: terraform-project2/ec2
        run: terraform init   

      - name: tflint setup
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.52.0

      - name: Init TFLint
        working-directory: terraform-project2/ec2
        run: tflint --init    

      - name: run tflint
        working-directory: terraform-project2/ec2
        id: tflint
        run: |
          tflint -f compac0t -no-color | tee tflint_op.txt
          echo "exitcode=$?" >> $GITHUB_OUTPUT

      - name: comment terraform TFLint
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            const fs = require('fs');
            const lint = fs.readFileSync('terraform-project2/ec2/tflint_op.txt', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## Terraform TFLint Output for \`ec2-instance\`
              \n\n\`\`\`hcl\n${lint}\n\`\`\``
              });

      - name: terraform format
        working-directory: terraform-project2/ec2
        run: terraform fmt 

      - name: terraform validate
        working-directory: terraform-project2/ec2
        run: terraform validate

  securityscan:
    runs-on: ubuntu-latest
    needs: terraformlint
    steps:

      - name: Checkout code
        uses: actions/checkout@v2 

      - name: configure aws   
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: terraform setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.12.0

      - name: terraform initialize
        id: init
        working-directory: terraform-project2/ec2
        run: terraform init

      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.2.0
        with:
          github_token: ${{ github.token }}

  terraform-plan:
    runs-on: ubuntu-latest                         
    needs: securityscan
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: configure aws 
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: terraform setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.12.0

      - name: terraform initialize
        id: init
        working-directory: terraform-project2/ec2
        run: terraform init

      - name: terraform plan
        id: plan
        working-directory: terraform-project2/ec2
        run: |
          terraform plan -out=tfplan -no-color | tee plan_output.txt
          echo "exitcode=$?" >> $GITHUB_OUTPUT

      - name: comment terraform plan
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            const fs = require('fs');
            const plan = fs.readFileSync('terraform-project2/ec2/plan_output.txt', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## Terraform Plan Output for \`ec2-instance\`
              \n\n\`\`\`hcl\n${plan}\n\`\`\``
            });

  artifact-build:
    runs-on: ubuntu-latest                    
    needs: terraform-plan
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: release artifact
        working-directory: terraform-project2/ec2
        run: |
          zip -r terraform-project2-ec2.zip . -x '*.git'
          mkdir -p release-artifacts
          mv terraform-project2-ec2.zip release-artifacts/

      - name: Create Semver Tag
        id: create_tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch

      - name: Create GitHub Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ steps.create_tag.outputs.new_tag }}
          prerelease: false
          title: "Release: ${{ steps.create_tag.outputs.new_tag }}"
          files: |
            terraform-project2/ec2/release-artifacts/terraform-project2-ec2.zip     

      - name: Comment on PR with new tag
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            A new tag `${{ steps.create_tag.outputs.new_tag }}` was created and pushed!
            repo-token: ${{ secrets.GITHUB_TOKEN }}
